### ISSUE TITLE
Add Staten Island Railway

### ISSUE THREAD

**Issue by dwvieira** [NYCPlanning/travelsheds#14]
Can you please add the line for the Staten Island Railway as a layer in the map? It seems to be including the SIR in the subway travel data.

Thanks!

**Comment by chriswhong** [comment]
Do you know where we can find a good line geometry for the SI railroad?  If we can't find one readily available we can produce one from the GTFS file itself.  

This should be an easy fix and requires maybe 1/2 hour.

**Comment by dwvieira** [comment]
See the attached file from MTA's website. It seems like "SI" is listed in the shapes.txt file. Can you give it a try and let me know how it works?
[google_transit.zip](https://github.com/NYCPlanning/travelsheds/files/500638/google_transit.zip)

**Comment by chriswhong** [comment]
I was able to pull data from [Baruch College's Transit Data Site](https://www.baruch.cuny.edu/confluence/display/geoportal/NYC+Mass+Transit+Spatial+Layers).  Added the SI railroad to the cartodb map layer displayed on the page, and it's live now.
