### ISSUE TITLE
If the last time cutoff is blank a travelshed will not be generated

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/travelsheds#9]

**Comment by chriswhong** [comment]
The components are based on an array, so it is probably just passing a null to the API call.  We can trim out nulls from the array so that it's still a valid api call.  The fix should be a general validation that the elements of the array are all numbers, and are unique

**Comment by chriswhong** [comment]
Fixed in 3b9d1ca9d216c4255cda9395cc0c54af8cd03fb2 by checking `Number.isInteger()` on each cutoff before appending query parameters to the API call.  Closing
